### ISSUE TITLE
[Frontend] UI/View - 自定义样式

### ISSUE THREAD

**Issue by martin-cao** [martin-cao/Lexify#21]
使用QSS
技术试验性质 如果可行就顺着往下搓

**Comment by martin-cao** [comment]
i'm idiot

**Comment by YingmoY** [comment]
不要忘记使用图形化编辑器的属性编辑器功能，可用直接在styleSheet中写入qss

**Comment by martin-cao** [comment]
ご提案いただき、誠にありがとうございます。頂いたご意見は非常に有益であり、今後の方針に反映できるかどうか慎重に検討させていただきます。引き続きご意見をお聞かせいただけますと幸いです。
